src/Entity/Events.php
<?php

namespace App\Entity;

use App\Repository\EventsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventsRepository::class)]
class Events
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_time = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $picture = null;

    #[ORM\Column]
    private ?int $capacity = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column]
    private ?int $phone = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column(length: 255)]
    private ?string $URL = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDateTime(): ?\DateTimeInterface
    {
        return $this->date_time;
    }

    public function setDateTime(\DateTimeInterface $date_time): static
    {
        $this->date_time = $date_time;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(int $capacity): static
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(int $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getURL(): ?string
    {
        return $this->URL;
    }

    public function setURL(string $URL): static
    {
        $this->URL = $URL;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }
}

src/Form/EventsType.php
<?php

namespace App\Form;

use App\Entity\Events;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', null, [
                'attr' => ['class' => 'form-control', 'placeholder' => 'Please enter the event name'],
            ])
            ->add('date_time', null, [
                'attr' => ['class' => 'form-control'],
                "widget" => "single_text"
            ])
            ->add('description', null, [
                'attr' => ['class' => 'form-control', 'placeholder' => 'Please describe the event'],
            ])
            ->add('picture', null, [
                'attr' => ['class' => 'form-control', 'placeholder' => 'Please enter the image URL'],
            ])
            ->add('capacity', null, [
                'attr' => ['class' => 'form-control', 'placeholder' => 'Please enter the capacity of people'],
            ])
            ->add('email', null, [
                'attr' => ['class' => 'form-control', 'placeholder' => 'Please enter the email'],
            ])
            ->add('phone', null, [
                'attr' => ['class' => 'form-control', 'placeholder' => 'Please enter the phone number'],
            ])
            ->add('address', null, [
                'attr' => ['class' => 'form-control', 'placeholder' => 'Please enter the location of the event'],
            ])
            ->add('URL', null, [
                'attr' => ['class' => 'form-control', 'placeholder' => 'Please enter the event URL'],
            ])
            ->add('type', ChoiceType::class, [
                'attr' => ['class' => 'form-control'],
                'choices'  => [
                    'Music' => 'music',
                    'Theater' => 'theater',
                    'Movie' => 'movie',
                    'Sport' => 'sport',
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Events::class,
        ]);
    }
}

src/Controller/EventsController.php
<?php

namespace App\Controller;

use App\Entity\Events;
use App\Form\EventsType;
use App\Repository\EventsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/events')]
class EventsController extends AbstractController
{
    #[Route('/', name: 'app_events_index', methods: ['GET'])]
    public function index(EventsRepository $eventsRepository): Response
    {
        return $this->render('events/index.html.twig', [
            'events' => $eventsRepository->findAll(),
        ]);
    }

    #[Route('/type', name: 'app_events_type', methods: ['GET'])]
    public function filter(Request $request, EventsRepository $eventsRepository): Response
    {
        $filterName = $request->query->get('type');
        $filteredEvents = $eventsRepository->findBy(['type' => $filterName]);
        return $this->render('events/index.html.twig', [
            'events' => $filteredEvents,
        ]);
    }

    #[Route('/new', name: 'app_events_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $event = new Events();
        $form = $this->createForm(EventsType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('app_events_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('events/new.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_events_show', methods: ['GET'])]
    public function show(Events $event): Response
    {
        return $this->render('events/show.html.twig', [
            'event' => $event,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_events_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Events $event, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EventsType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_events_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('events/edit.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_events_delete', methods: ['POST'])]
    public function delete(Request $request, Events $event, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $event->getId(), $request->request->get('_token'))) {
            $entityManager->remove($event);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_events_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>
			{% block title %}Events in Vienna
			{% endblock %}
		</title>
		<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"> {% block stylesheets %}{% endblock %}{% block javascripts %}{% endblock %}
		</head>
		<body>

			{% include "components/navbar.html.twig" %}

			{% block body %}{% endblock %}

			{% include "components/footer.html.twig" %}


			<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
		</body>
	</html>

templates/components/footer.html.twig
<footer class="bg-danger text-white border">
	<div class="text-center pt-1">
		<a class="p-3 text-decoration-none text-white" href="/events">
			Home
		</a>
		<span>|</span>
		<a class="p-3 text-decoration-none text-white" href="/events/new">
			Create
		</a>
		<span>|</span>
		<a class="p-3 text-decoration-none text-white" href="/events">
			All events
		</a>
	</div>
	<div class="text-center pt-2 pb-1">
		<span>&copy; Copyright Arbër Islamaj</span>
	</div>
</footer>

templates/components/hero.html.twig
<img src="{{ asset('images/hero.jpg') }}" alt="">

templates/components/navbar.html.twig
<nav class="navbar navbar-expand-lg bg-danger">
	<div class="container-fluid">
		<a class="navbar-brand text-white" href="/events">Events</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNavDropdown">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link active text-white" aria-current="page" href="/events/new">Create</a>
				</li>
				<li class="nav-item">
					<a class="nav-link text-white" href="#">Features</a>
				</li>
				<li class="nav-item">
					<a class="nav-link text-white" href="#">Pricing</a>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
						Event type
					</a>
					<ul class="dropdown-menu">
						<li>
							<a class="dropdown-item" href="{{ path('app_events_type', {'type': 'music'}) }}">Music</a>
						</li>
						<li>
							<a class="dropdown-item" href="{{ path('app_events_type', {'type': 'theater'}) }}">Theater</a>
						</li>
						<li>
							<a class="dropdown-item" href="{{ path('app_events_type', {'type': 'movie'}) }}">Movie</a>
						</li>
						<li>
							<a class="dropdown-item" href="{{ path('app_events_type', {'type': 'sport'}) }}">Sport</a>
						</li>
					</ul>
				</li>
			</ul>
		</div>
	</div>
</nav>

templates/events/_delete_form.html.twig
<form method="post" action="{{ path('app_events_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
	<button class="btn btn-danger">Delete</button>
</form>

templates/events/_form.html.twig
<div class="container w-75">
	{{ form_start(form) }}
	{{ form_widget(form) }}
	<button class="btn btn-success m-2">{{ button_label|default('Save') }}</button>
	{{ form_end(form) }}
</div>

templates/events/_type.html.twig
{# templates/events/_type.html.twig #}

<h1>Events of Type
	{{ selectedType }}</h1>

<ul>
	{% for event in events %}
		<div class="p-2">
			<div class="card">
				<img src="{{ event.picture }}" class="card-img-top" alt="{{ event.name }}">
				<div class="card-body">
					<h5 class="card-title">Event name:
						{{ event.name }}</h5>
				</div>
				<ul class="list-group list-group-flush">
					<li class="list-group-item">Type:
						{{ event.Type }}</li>
					<li class="list-group-item">Date & time:
						{{ event.dateTime ? event.dateTime|date('Y-m-d H:i:s') : '' }}</li>
					<li class="list-group-item">Location:
						{{ event.address }}</li>
				</ul>
				<div class="d-flex justify-content-evenly m-1">
					<a class="btn btn-primary" href="{{ path('app_events_show', {'id': event.id}) }}" class="card-link">Details</a>
					<a class="btn btn-warning" href="{{ path('app_events_edit', {'id': event.id}) }}" class="card-link">Update</a>
					<a target="_blank" class="btn btn-primary" href="{{ event.URL }}" class="card-link">Event URL</a>

				</div>
			</div>
		</div>
	{% endfor %}
</ul>

templates/events/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Events
{% endblock %}

{% block body %}
	<h1 class="m-3 text-center">Edit Events</h1>

	{{ include('events/_form.html.twig', {'button_label': 'Update'}) }}

	<a class="btn btn-warning" href="{{ path('app_events_index') }}">All events</a>

	{{ include('events/_delete_form.html.twig') }}
{% endblock %}

templates/events/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Events
{% endblock %}

{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('css/style.css') }}">
{% endblock %}
{% block body %}
	{% include "components/hero.html.twig" %}

	<div class="container">

		<h1 class="m-3 text-center">Events in Vienna</h1>

		<div class="row row-cols-lg-4 row-cols-md-3 row-cols-sm-2 row-cols-xs-1">

			{% for event in events %}

				<div class="p-2">
					<div class="card">
						<img src="{{ event.picture }}" class="card-img-top" alt="{{ event.name }}">
						<div class="card-body">
							<h5 class="card-title">Event name:
								{{ event.name }}</h5>
						</div>
						<ul class="list-group list-group-flush">
							<li class="list-group-item">Type:
								{{ event.Type }}</li>
							<li class="list-group-item">Date & time:
								{{ event.dateTime ? event.dateTime|date('Y-m-d H:i:s') : '' }}</li>
							<li class="list-group-item">Location:
								{{ event.address }}</li>
						</ul>
						<div class="d-flex justify-content-evenly m-1">
							<a class="btn btn-primary" href="{{ path('app_events_show', {'id': event.id}) }}" class="card-link">Details</a>
							<a class="btn btn-warning" href="{{ path('app_events_edit', {'id': event.id}) }}" class="card-link">Update</a>
							<a target="_blank" class="btn btn-primary" href="{{ event.URL }}" class="card-link">Event URL</a>

						</div>
					</div>
				</div>

			{% else %}
				<p>no events found</p>
			{% endfor %}

		</div>

		<a class="btn btn-warning mt-5 mb-5" href="{{ path('app_events_new') }}">Create new</a>

	</div>

{% endblock %}

templates/events/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Events
{% endblock %}

{% block body %}
	<h1 class="m-3 text-center">Create a new Event</h1>

	{{ include('events/_form.html.twig') }}

	<a class="btn btn-warning m-5" href="{{ path('app_events_index') }}">All events</a>
{% endblock %}

templates/events/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Events
{% endblock %}

{% block body %}

	<div class="container">

		<h1 class="m-3 text-center">Event details</h1>

		<div class="card mb-3">
			<img src="{{ event.picture }}" class="card-img-top" alt="{{ event.name }}">
			<div class="card-body">
				<h5 class="card-title">Event name:
					{{ event.name }}</h5>
				<p class="card-text">Type:
					{{ event.Type }}</p>
				<p class="card-text">Description:
					{{ event.description }}</p>
				<p class="card-text">Date & Time:
					{{ event.dateTime ? event.dateTime|date('Y-m-d H:i:s') : '' }}</p>
				<p class="card-text">Location:
					{{ event.address }}</p>
				<p class="card-text">Capacity:
					{{ event.capacity }}</p>
				<p class="card-text">Email:
					{{ event.email }}</p>
				<p class="card-text">Tel:
					{{ event.phone }}</p>

				<div class="d-flex justify-content-evenly border-top pt-3">
					<a class="btn btn-warning" href="{{ path('app_events_index') }}">All events</a>
					<a class="btn btn-primary" href="{{ event.URL }}">Event URL</a>
					<a class="btn btn-warning" href="{{ path('app_events_edit', {'id': event.id}) }}">Update event</a>
					<a>{{ include('events/_delete_form.html.twig') }}</a>
				</div>

			</div>
		</div>
	</div>

{% endblock %}

templates/events/type.html.twig
{# templates/events/_type.html.twig

<h1>Events of Type
	{{ selectedType }}</h1>

<ul>
	{% for event in events %}
		<div class="p-2">
			<div class="card">
				<img src="{{ event.picture }}" class="card-img-top" alt="{{ event.name }}">
				<div class="card-body">
					<h5 class="card-title">Event name:
						{{ event.name }}</h5>
				</div>
				<ul class="list-group list-group-flush">
					<li class="list-group-item">Type:
						{{ event.Type }}</li>
					<li class="list-group-item">Date & time:
						{{ event.dateTime ? event.dateTime|date('Y-m-d H:i:s') : '' }}</li>
					<li class="list-group-item">Location:
						{{ event.address }}</li>
				</ul>
				<div class="d-flex justify-content-evenly m-1">
					<a class="btn btn-primary" href="{{ path('app_events_show', {'id': event.id}) }}" class="card-link">Details</a>
					<a class="btn btn-warning" href="{{ path('app_events_edit', {'id': event.id}) }}" class="card-link">Update</a>
					<a target="_blank" class="btn btn-primary" href="{{ event.URL }}" class="card-link">Event URL</a>

				</div>
			</div>
		</div>
	{% endfor %}
</ul> #}